---
# tasks file for php

- name: Install php-fpm
  ansible.builtin.apt:
    name: php-fpm
    state: latest

- name: Enable php-fpm
  ansible.builtin.service:
    name: php8.2-fpm
    state: started
    enabled: yes
  
- name: Remove php-fpm.cfg
  ansible.builtin.template:
    src: www.conf.j2
    dest: /etc/php/8.2/fpm/pool.d/www.conf
  notify: Restart php-fpm
