# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'

BOX_IMAGE = "ubuntu/jammy64"
MEMORY = "2048"
CPU = "2"

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "ubuntu"
    subconfig.vm.network :private_network, ip: "192.168.56.11"

    #Create shared folder
    subconfig.vm.synced_folder "/home/admin1/scripts", "/scripts"

    subconfig.vm.provider :virtualbox do |vb|
      vb.memory = MEMORY
      vb.cpus = CPU
      #vb.customize ["modifyvm", id:, "--memory", MEMORY]
      #vb.customize ["modifyvm", id:, "--cpus", CPU]
    end    
  end
  #Install some additional packages
  config.vm.provision "shell", inline: <<-SHELL
    sudo su
    sed 's/#PasswordAuthentication yes/PasswordAuthentication yes/g'
    systemctl restart sshd.service
    apt-get update
    apt-get upgrade
    apt-get install -y python3 python3-pip
    pip install django --break-system-packages
    pip install psycopg2 --break-system-packages
    #Install Postgresql
    sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    apt-get -y install postgresql 
    SHELL
end