version: '3'

services:
  nginx:
    image: "nginx:latest"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
      - ./www:/var/www
    ports:
      - 8080:80 
    networks:
      - internal

  php:
    build: .
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://nginx | grep -c works > /dev/null"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./www:/var/www
    networks:
      - internal

networks:
  internal:
    driver: bridge



