FROM python:3.7-alpine
WORKDIR /srv/app
COPY ./requirements.txt /
RUN apk add libpq-dev gcc
RUN pip install -r /requirements.txt
COPY ./web.py ./
COPY ./web.conf ./conf/
CMD ["python", "web.py"]

#Another Docerfile
#FROM python:3
#WORKDIR /srv/app
#COPY ./requirements.txt /srv/app
#RUN pip3 install -r ./requirements.txt
#COPY ./web.py ./
#COPY ./web.conf ./conf/
#CMD ["python", "web.py"]