version: '3.2'

volumes:
  grafana-storage: {} 

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert.rules:/etc/prometheus/alert.rules:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    depends_on:
      - node-exporter
    restart: always

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    hostname: monitoring
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    restart: always

  blackbox-exporter:
    container_name: blackbox-exporter
    image: prom/blackbox-exporter
    volumes:
      - ./blackbox/blackbox.yml:/config/blackbox.yml:ro
    command: --config.file=/config/blackbox.yml
    ports:
      - 9115:9115
    restart: always

  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    restart: unless-stopped  
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana

  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager:/etc/alertmanager
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  alertmanager-bot:
    container_name: alertmanager-bot   
    command:
      - --alertmanager.url=http://localhost:9093
      - --log.level=info
      - --store=bolt
      - --bolt.path=/data/bot.db
    environment:
      TELEGRAM_ADMIN: "884174870"
      TELEGRAM_TOKEN: 7094254109:AAF1KYBKvInh252FPJAaq0gG3EeH1qmnUFI
    image: metalmatze/alertmanager-bot:latest
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./data:/data
