---
# tasks file for docker 
- name: Install dependencies Docker на Ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add GPG for Docker  Ubuntu
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker repository Ubuntu
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: docker

- name: Install Docker Ubuntu/CentOS
  ansible.builtin.package:
    name: docker-ce
    state: present

- name: Run Docker
  ansible.builtin.service:
    name: docker
    state: started