apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Namespace }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: {{ .Release.Namespace }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: {{ .Release.Namespace }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: {{ .Values.nginx.resources.limits.memory }}
            cpu: {{ .Values.nginx.resources.limits.cpu }}
          requests:
            memory: {{ .Values.nginx.resources.requests.memory }}
            cpu: {{ .Values.nginx.resources.requests.cpu }}  
        ports:
        - containerPort: 80